# Generated by Django 3.2.8 on 2021-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
