# Generated by Django 3.2.8 on 2021-11-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscriptions_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscriptions',
        ),
    ]
