# Generated by Django 3.2.8 on 2021-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
