# Generated by Django 3.2.8 on 2021-11-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
