# Generated by Django 3.2.8 on 2021-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_videos_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_vids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
