# Generated by Django 3.2.8 on 2021-10-29 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(related_name='course_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
