# Generated by Django 3.2.8 on 2021-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
