# Generated by Django 3.2.8 on 2021-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_likecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecourse',
            name='value',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
